name: graytalk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.4
  flutter_colorpicker: ^1.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/imgs/intro/
